target 'Rappi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '4.8.2'
  pod 'Tagged', '~> 0.4'
  pod 'PromiseKit', '6.8.4'
  pod 'SkeletonView', '1.5'

  target 'RappiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
